# ============================================================
# Configuration du Trip Management Service
# Nom du service : smart-mobility-trip-service
# Port           : 8082
# ============================================================

server:
  port: 8082

spring:
  application:
    name: smart-mobility-trip-service

  datasource:
    url: ${TRIP_DB_URL:jdbc:h2:mem:tripdb}
    username: ${TRIP_DB_USER:sa}
    password: ${TRIP_DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
