# ============================================================
# Configuration du User & Mobility Pass Service
# Nom du service : smart-mobility-user-service
# Port           : 8081
# ============================================================

server:
  port: 8081

spring:
  application:
    name: smart-mobility-user-service

  # --- Base de données (valeurs surchargeables par profil) ---
  datasource:
    url: ${USER_DB_URL:jdbc:mysql://localhost:3306/userdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${USER_DB_USER:root}
    password: ${USER_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
