# ============================================================
# Configuration du Trip Management Service
# Nom du service : smart-mobility-trip-service
# Port           : 8082
# ============================================================

server:
  port: 8082

spring:
  application:
    name: smart-mobility-trip-service

  datasource:
    url: ${TRIP_DB_URL:jdbc:mysql://localhost:3306/tripdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${TRIP_DB_USER:root}
    password: ${TRIP_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
