# ============================================================
# Configuration du User & Mobility Pass Service
# Nom du service : smart-mobility-user-service
# Port           : 8081
# ============================================================

server:
  port: 8081

spring:
  application:
    name: smart-mobility-user-service

  # --- Base de données (valeurs surchargeables par profil) ---
  datasource:
    url: ${USER_DB_URL:jdbc:h2:mem:userdb}
    username: ${USER_DB_USER:sa}
    password: ${USER_DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
