# ============================================================
# Configuration du Trip Management Service
# Nom du service : smart-mobility-trip-service
# Port           : 8082
# ============================================================

server:
  port: 8082

spring:
  application:
    name: smart-mobility-trip-service

  datasource:
    url: ${TRIP_DB_URL:jdbc:mysql://localhost:3306/tripdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${TRIP_DB_USER:root}
    password: ${TRIP_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # --- RabbitMQ : connexion au broker de messages ---
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# --- Resilience4j : activer le circuit breaker Feign ---
feign:
  circuitbreaker:
    enabled: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        registerHealthIndicator: true
    instances:
      smart-mobility-network-service:
        baseConfig: default
      smart-mobility-pricing-service:
        baseConfig: default
      smart-mobility-billing-service:
        baseConfig: default
      smart-mobility-user-service:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
    instances:
      smart-mobility-network-service:
        baseConfig: default
      smart-mobility-pricing-service:
        baseConfig: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,env
