# ============================================================
# Profil PROD — API Gateway
# ============================================================

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: ${ALLOWED_ORIGINS:https://smart-mobility.example.com}
            allowCredentials: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        waitDurationInOpenState: 10s
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s

logging:
  level:
    org.springframework.cloud.gateway: WARN
    reactor.netty: WARN
