# ============================================================
# Profil TEST — API Gateway
# ============================================================

eureka:
  client:
    enabled: false

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: WARN
