# ============================================================
# Configuration du Billing Service
# Nom du service : smart-mobility-billing-service
# Port           : 8084
# ============================================================

server:
  port: 8084

spring:
  application:
    name: smart-mobility-billing-service

  datasource:
    url: ${BILLING_DB_URL:jdbc:mysql://localhost:3306/billingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${BILLING_DB_USER:root}
    password: ${BILLING_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # --- RabbitMQ : connexion au broker de messages ---
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# --- Seuil d'alerte solde faible (en FCFA) ---
billing:
  low-balance-threshold: 500

# --- Resilience4j : activer le circuit breaker Feign ---
feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        registerHealthIndicator: true
    instances:
      smart-mobility-trip-service:
        baseConfig: default
      smart-mobility-pricing-service:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
    instances:
      smart-mobility-pricing-service:
        baseConfig: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers

paydunya:
  master-key: wBRGbm0a-oJfE-rPde-5sxs-sGp29n0gidhC
  private-key: test_private_hFuKyADuNb7DwjA8RIicC4LkvsE
  token: onX8YemlrMeSNcR07PvB
  sandbox: true
  store-name: "Smart Mobility Pass"
  callback-url: ${GATEWAY_URL:https://b11c-154-125-65-72.ngrok-free.app}/api/billing/recharge/callback
  return-url: ${GATEWAY_URL:https://b11c-154-125-65-72.ngrok-free.app}/api/billing/recharge/return
  cancel-url: ${GATEWAY_URL:https://b11c-154-125-65-72.ngrok-free.app}/api/billing/recharge/cancel

