# ============================================================
# Profil DEV — API Gateway
# ============================================================

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
